### ISSUE TITLE
Instrucciones de Uso

### ISSUE THREAD

**Issue by stompy-lizard** [robz25/Proyecto1_IE0724#11]
El readme dejarlo bien bonito y claro que es lo qué hace y cómo se hace.

También debería dejar claro los requisitos del sistema.

¿Algo más?

_Según el enunciado debería llamarse README, sin el .md, pero no creo que haya problema con eso(¿un mensaje al profe? solo para estar seguros)._

**Comment by robz25** [comment]
Readme listo
